on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@HEAD
    - run: |
       curl -L https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz | sudo tar xz -C /usr/local/bin oras
       oras login -u '${{github.actor}}' -p '${{secrets.GITHUB_TOKEN}}' ghcr.io
       oras push --disable-path-validation 'ghcr.io/${{github.repository}}' /etc/os-release:application/octet-stream
